format_version: 10
pipelines:
  good:
    group: aaaa
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-fc0dbb6:
        git: https://github.com/SeungHoonJeon/cicd-test-private-.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - good:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          good:
            timeout: 0
            tasks:
            - exec:
                command: id
                run_if: passed
